package com.cpputest.manager;

import java.io.ByteArrayInputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IFolder;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.Path;

import com.cpputest.manager.model.TestCase;
import com.cpputest.manager.model.TestGroup;
import com.cpputest.manager.model.TestProject;

public class TestRunnerGenerator {
    public static void generateCppUTestRun(String projectName, Object[] checkedElements, TestProject testProject) {
        // 高速判定のために配列を Set に変換
        Set<Object> checkedSet = new HashSet<Object>(Arrays.asList(checkedElements));
        // プロジェクトを取得
        IProject project = ResourcesPlugin.getWorkspace().getRoot().getProject(projectName);

        if (!project.exists()) {
            System.err.println("Project not found: " + projectName);
            return;
        }

        // e2studioのGCC_ARMの場合だけinitialise_monitor_handlesを呼ぶコードを追加する
        CppUTestSetupHandler.EnvironmentType environment = CppUTestSetupHandler.getEnvironmentType();
        CppUTestSetupHandler.ToolchainType toolChain = CppUTestSetupHandler.getToolchainType(project);
        System.out.println("Environment: " + environment + ", ToolchainType: " + toolChain);
        boolean appendInitialiseMonitorHandles = (toolChain == CppUTestSetupHandler.ToolchainType.GCC_ARM);
        
        try {
            // src/cpputest_gen フォルダの取得と作成
            IFolder folder = project.getFolder(new Path("src/cpputest_gen"));

            if (!folder.exists()) {
                folder.create(true, true, null);
            }

            // 生成するファイルの内容
            StringBuilder sb = new StringBuilder();
            sb.append("// This file is auto-generated by CppUTest Plugin. Do not edit.\n\n");
            sb.append("#include \"CppUTest/CommandLineTestRunner.h\"\n");
            sb.append("#include \"CppUTestRun.h\"\n\n");
            if (appendInitialiseMonitorHandles) {
                sb.append("extern \"C\" void initialise_monitor_handles(void);\n\n");
            }
            sb.append("void CppUTestRun(void) {\n");

            if (appendInitialiseMonitorHandles) {
                sb.append("    initialise_monitor_handles();\n\n");
            }
            
            // CppUTestは "-st GroupName.TestName" で実行するテストを絞り込む
            sb.append("    const char* args[] = {\"test\", \"-v\"");

            // 全グループ・全テストケースが選択されているか確認
            boolean allSelected = true;
            for (TestGroup testGroup : testProject) {
                for (TestCase tc : testGroup.getCases()) {
                    if (!checkedSet.contains(tc)) {
                        allSelected = false;
                        break;
                    }
                }
                if (!allSelected) break;
            }

            // 引数の生成処理（全選択の場合は-sg/-stを付けない）
            if (!allSelected) {
                for (TestGroup testGroup : testProject) {
                    List<TestCase> selectedCases = new ArrayList<TestCase>();
                    for (TestCase tc : testGroup.getCases()) {
                        if (checkedSet.contains(tc)) {
                            selectedCases.add(tc);
                        }
                    }
                    if (selectedCases.isEmpty()) {
                        // グループ内で選択されているテストケースが無い場合はスキップ
                        continue;
                    }
                    if (selectedCases.size() == testGroup.getCases().size()) {
                        // グループ全体が選択されている場合はグループで指定する
                        sb.append(("\n        , \"-sg\", \"") + testGroup.getName() + "\"");
                        continue;
                    }
                    for (TestCase tc : selectedCases) {
                        sb.append(("\n        , \"-st\", \"") + testGroup.getName() + "." + tc.getName() + "\"");
                    }
                }
            }

            sb.append("};\n");
            sb.append("    CommandLineTestRunner::RunAllTests(sizeof(args)/sizeof(char*), (char**)args);\n");
            sb.append("}");

            // ファイルの保存
            IFile file = folder.getFile("CppUTestRun.cpp");
            ByteArrayInputStream stream = new ByteArrayInputStream(sb.toString().getBytes());

            if (file.exists()) {
                file.setContents(stream, true, true, null);
            } else {
                file.create(stream, true, null);
            }

            // プロジェクトをリフレッシュ
            project.refreshLocal(IProject.DEPTH_INFINITE, null);

        } catch (CoreException e) {
            e.printStackTrace();
        }
    }
    

}