package com.cpputest.manager;

import java.io.ByteArrayInputStream;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IFolder;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.Path;

import com.cpputest.manager.view.TestResultView.TestCase;
import com.cpputest.manager.view.TestResultView.TestGroup;
import com.cpputest.manager.view.TestResultView.TestProject;

public class TestRunnerGenerator {

    public static void generateCppUTestRun(String projectName, Object[] checkedElements, TestProject testProject) {
     // 高速判定のために配列を Set に変換（お作法）
        Set<Object> checkedSet = new HashSet<>(Arrays.asList(checkedElements));
        
        // 1. プロジェクトを取得
        IProject project = ResourcesPlugin.getWorkspace().getRoot().getProject(projectName);

        if (!project.exists()) {
            System.err.println("Project not found: " + projectName);
            return;
        }

        try {
            // 2. src/cpputest_gen フォルダの取得と作成
            IFolder folder = project.getFolder(new Path("src/cpputest_gen"));

            if (!folder.exists()) {
                folder.create(true, true, null);
            }

            // 3. 生成するファイルの内容
            StringBuilder sb = new StringBuilder();
            sb.append("// This file is auto-generated by CppUTest Plugin. Do not edit.\n\n");
            sb.append("#include \"CppUTest/CommandLineTestRunner.h\"\n");
            sb.append("#include \"CppUTestRun.h\"\n\n");
            sb.append("void CppUTestRun(void) {\n");

            // CppUTestは "-st GroupName.TestName" で実行するテストを絞り込む
            sb.append("    const char* args[] = {\"test\", \"-v\"");

            // 引数の生成処理
            for (TestGroup gp : testProject) {
                // そのグループ内の「チェックされているテスト」を抽出
                List<TestCase> selectedInGroup = gp.getCases().stream().filter(tc -> checkedSet.contains(tc)).collect(Collectors.toList());
                if (selectedInGroup.isEmpty()) {
                    continue; // このグループは何も選ばれていない
                }

                // 「グループ全選択」か「個別選択」かを判定
                if (selectedInGroup.size() == gp.getCases().size()) {
                    // 全件選択なら -g
                    sb.append("\n        , \"-g\", \"").append(gp.getName()).append("\"");
                } else {
                    // 一部なら -st
                    for (TestCase tc : selectedInGroup) {
                        sb.append("\n        , \"-st\", \"").append(tc.getFullName()).append("\"");
                    }
                }
            }

            sb.append("};\n");
            sb.append("    CommandLineTestRunner::RunAllTests(sizeof(args)/sizeof(char*), (char**)args);\n");
            sb.append("}");

            // ファイルの保存
            IFile file = folder.getFile("CppUTestRun.cpp");
            ByteArrayInputStream stream = new ByteArrayInputStream(sb.toString().getBytes());

            if (file.exists()) {
                file.setContents(stream, true, true, null);
            } else {
                file.create(stream, true, null);
            }

            // プロジェクトをリフレッシュ
            project.refreshLocal(IProject.DEPTH_INFINITE, null);

        } catch (CoreException e) {
            e.printStackTrace();
        }
    }

    /**
     * フォルダが存在しない場合、親フォルダを含めて作成するヘルパー
     */
//    private static void prepareFolder(IFolder folder) throws CoreException {
//        if (!folder.exists()) {
//            if (folder.getParent() instanceof IFolder) {
//                prepareFolder((IFolder) folder.getParent());
//            }
//            folder.create(true, true, null);
//        }
//    }
}