// This file is auto-generated by CppUTest Plugin. Do not edit.
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

#include "CppUTest/CommandLineTestRunner.h"

int main(void) {
    const char* args[] = {"test", "-v"};
    return CommandLineTestRunner::RunAllTests(sizeof(args)/sizeof(char*), (char**)args);
}

#ifdef __cplusplus

extern "C" {
void abort(void)
{
}
}
#endif
