// This file is auto-generated by CppUTest Plugin. Do not edit.

#include "CppUTest/CommandLineTestRunner.h"
#include "GeneratedMain.h"

void CppUTestMain(void) {
    const char* args[] = {"test", "-v"};
    CommandLineTestRunner::RunAllTests(sizeof(args)/sizeof(char*), (char**)args);
}