package com.example.cpputest;

import java.io.ByteArrayInputStream;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IFolder;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;

import com.example.cpputest.view.TestResultView.TestCase;

public class TestRunnerGenerator {

    public static void generateMain(String projectName, Object[] selectedTests) {
        // 1. プロジェクトを取得
        IProject project = ResourcesPlugin.getWorkspace().getRoot().getProject(projectName);
        
        if (!project.exists()) {
            System.err.println("Project not found: " + projectName);
            return;
        }

        try {
            // 2. src/cpputest_gen フォルダの取得と作成
            IFolder folder = project.getFolder(new Path("src/cpputest_gen"));
            prepareFolder(folder);

            // 3. 生成するファイルの内容
            StringBuilder sb = new StringBuilder();
            sb.append("// This file is auto-generated by CppUTest Plugin. Do not edit.\n");
            sb.append("#ifdef __cplusplus\nextern \"C\" {\nvoid abort(void);\n}\n#endif\n\n");
            sb.append("#include \"CppUTest/CommandLineTestRunner.h\"\n\n");
            sb.append("int main(int ac, char** av) {\n");
            
            // CppUTestは "-g GroupName" でグループ絞り込みが可能です
            sb.append("    const char* args[] = {\"test\", \"-v\"");
            
            if (selectedTests == null || selectedTests.length == 0) {
                // 何も選択されていない
            } else {
                // 選択されたテストがある場合、引数をシミュレートする
                for (Object obj : selectedTests) {
                    // TestResultView.TestCase クラスのインスタンスと想定
                    // -st <group>.<testName> で実行するテストを指定する
                	TestCase tc = (TestCase)obj;
                    sb.append(", \"-st\", \"" + tc.getFullName() + "\"");
                }
            }
            
            sb.append("};\n");
            sb.append("    return CommandLineTestRunner::RunAllTests(sizeof(args)/sizeof(char*), (char**)args);\n");
            
            sb.append("}\n\n");
            sb.append("#ifdef __cplusplus\n\nextern \"C\" {\nvoid abort(void)\n{\n}\n}\n#endif\n");

            // 4. ファイルの保存
            IFile file = folder.getFile("generated_main.cpp");
            ByteArrayInputStream stream = new ByteArrayInputStream(sb.toString().getBytes());
            
            if (file.exists()) {
                file.setContents(stream, true, true, null);
            } else {
                file.create(stream, true, null);
            }

            // プロジェクトをリフレッシュ
            project.refreshLocal(IProject.DEPTH_INFINITE, null);

        } catch (CoreException e) {
            e.printStackTrace();
        }
    }

    /**
     * フォルダが存在しない場合、親フォルダを含めて作成するヘルパー
     */
    private static void prepareFolder(IFolder folder) throws CoreException {
        if (!folder.exists()) {
            if (folder.getParent() instanceof IFolder) {
                prepareFolder((IFolder) folder.getParent());
            }
            folder.create(true, true, null);
        }
    }
}